### ISSUE TITLE
receipt order

### ISSUE THREAD

**Issue by andymckay** [rtilder/signing-service#2]
Can I check we've got the order on receipts right, according to: https://wiki.mozilla.org/Apps/WebApplicationReceipt#Firefox_Marketplace_receipts and https://github.com/andymckay/receipts/blob/master/receipts/receipts.py#L37 the first half is the receipt, the second half is the cert.

Does this https://github.com/andymckay/signing-service/blob/master/signing_service/receipts/views.py#L53-L54 have them the other way around?

**Comment by rtilder** [comment]
I appear to have totally brain farted when converting that from the old trunion code.  Definitely incorrect here.

**Comment by rtilder** [comment]
Fixed in pull #4
